apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: nginx-deployment 
  labels:
    app: nginx  #these labels are for Deployment itself not for pod
spec:
  replicas: 5 
  selector:
    matchLabels:
      app: nginx 
  template:
    metadata: 
      labels:
        app: nginx  # these labels are for pods
    spec:
      containers:
        - name: nginx 
          image: nginx:1.27.1-alpine
          ports:
            - containerPort: 80 

