apiVersion: v1 
kind: Pod 
metadata:
  name: nginx-pod 
  labels:
    app: nginx 
  annotations: 
    description: "Nginx od for learning"
spec:
  containers:
  - image: nginx:1.27.0
    name: nginx-container 
    ports: 
    - containerPort: 80

