apiVersion: v1 
kind: Pod 
metadata:
  name: nginx-pod 
  labels:
    app: nginx 
  annotations: 
    description: "Nginx od for learning"
spec:
  containers:
  - image: nginx:1.27.0
    name: nginx-container 
    ports: 
    - containerPort: 80


---

apiVersion: v1
kind: Service 
metadata:
  name: nginx-svc
  labels:
    app: nginx 
spec:
  type: NodePort
  ports:
  - port: 80 #service port
    protocol: TCP
    targetPort: 80 #container port
  selector:
    app: nginx