apiVersion: v1
kind: Service 
metadata:
  name: nginx-svc
  labels:
    app: nginx 
spec:
  type: NodePort
  ports:
  - port: 80 #service port
    protocol: TCP
    targetPort: 80 #container port
  selector:
    app: nginx

#kubectl expose pod nginx-pod --type=NodePort --port=80
#executed using config file whcih is similar to imperative management using CLI as commented above